### ISSUE TITLE
FOUND 23

### ISSUE THREAD

**Issue by ashraful1980** [Mizogg/Python-WebServer#2]
I have found as below:
Found [ 23 ]    Pages checked: 8577   Total addresses scanned: 2195712 from scanning http://194.163.146.206:3333/ @ Start PilotSeq
![Found](https://user-images.githubusercontent.com/52574658/172122289-57eecabd-baa4-4b53-b13e-43ff3b91ac04.jpg)

Attached herewith screenshot for your reference....
Please let me know where it is stored....

**Comment by Mizogg** [comment]
The problem is it meant to run on your server and save results on your server or pc or laptop. If many people are scanning then it reports false. On first page and on quite a few low range pages are the found puzzles and test Eth bc1 wallet. If someone goes to these pages a winner will be found. For those scanning at that moment in time get the report that if has found as well. I have attached the found file from yesterday You can see what I mean. 
[found.txt](https://github.com/Mizogg/Python-WebServer/files/8845655/found.txt)
